--pistol
data.raw.recipe["pistol-magazine-bismuth"].order = "a[basic-clips]-a01[pistol-magazine]b"
data.raw.recipe["firearm-magazine"].subgroup = "ammo-pistol"
data.raw.recipe["piercing-rounds-magazine"].subgroup = "ammo-pistol"
data.raw.recipe["pistol-magazine-bismuth"].subgroup = "ammo-pistol"
--rifle
data.raw.recipe["rifle-magazine-bismuth"].order = "a[basic-clips]-a03[rifle-magazine][bismuth]"
data.raw.recipe["rifle-magazine"].subgroup = "ammo-rifle"
data.raw.recipe["rifle-magazine-bismuth"].subgroup = "ammo-rifle"
data.raw.recipe["armor-piercing-rifle-magazine"].subgroup = "ammo-rifle"
data.raw.recipe["explosive-rounds-rifle-magazine"].subgroup = "ammo-rifle"
data.raw.recipe["uranium-rifle-magazine"].subgroup = "ammo-rifle"
data.raw.recipe["imersite-rifle-magazine"].subgroup = "ammo-rifle"
data.raw.recipe["rfw-fusion-rounds-magazine"].subgroup = "ammo-rifle"
data.raw.recipe["rfw-antimatter-rounds-magazine"].subgroup = "ammo-rifle"
--data.raw.recipe["plutonium-rounds-magazine"].subgroup = "ammo-rifle"
--Anti-materiel Rifle
data.raw.recipe["anti-material-rifle-magazine"].subgroup = "ammo-antimaterielrifle"
data.raw.recipe["armor-piercing-anti-material-rifle-magazine"].subgroup = "ammo-antimaterielrifle"
data.raw.recipe["explosive-rounds-anti-material-rifle-magazine"].subgroup = "ammo-antimaterielrifle"
data.raw.recipe["uranium-anti-material-rifle-magazine"].subgroup = "ammo-antimaterielrifle"
data.raw.recipe["imersite-anti-material-rifle-magazine"].subgroup = "ammo-antimaterielrifle"
data.raw.recipe["rfw-fusion-anti-material-rifle-magazine"].subgroup = "ammo-antimaterielrifle"
data.raw.recipe["rfw-antimatter-anti-material-rifle-magazine"].subgroup = "ammo-antimaterielrifle"
--Shotgun
data.raw.recipe["shotgun-shell"].subgroup = "ammo-shotgun"
data.raw.recipe["piercing-shotgun-shell"].subgroup = "ammo-shotgun"
data.raw.recipe["rfw-uranium-shotgun-shell"].subgroup = "ammo-shotgun"
data.raw.recipe["rfw-imersite-shotgun-shell"].subgroup = "ammo-shotgun"
data.raw.recipe["rfw-fusion-shotgun-shell"].subgroup = "ammo-shotgun"
data.raw.recipe["rfw-antimatter-shotgun-shell"].subgroup = "ammo-shotgun"
--impulse
data.raw.recipe["impulse-rifle-ammo"].subgroup = "ammo-impulse"
--railgun
data.raw.recipe["se-railgun-ammo"].subgroup = "ammo-railgun"
--Shells
data.raw.recipe["cannon-shell"].subgroup = "ammo-shell"
data.raw.recipe["explosive-cannon-shell"].subgroup = "ammo-shell"
data.raw.recipe["uranium-cannon-shell"].subgroup = "ammo-shell"
data.raw.recipe["explosive-uranium-cannon-shell"].subgroup = "ammo-shell"
data.raw.recipe["rfw-fusion-cannon-shell"].subgroup = "ammo-shell"
data.raw.recipe["rfw-antimatter-cannon-shell"].subgroup = "ammo-shell"
--data.raw.recipe["plutonium-cannon-shell"].subgroup = "ammo-shell"
--data.raw.recipe["plutonium-cannon-shell"].order = "d[cannon-shell]-c[plutonium]"
--data.raw.recipe["explosive-plutonium-cannon-shell"].subgroup = "ammo-shell"
--data.raw.recipe["explosive-plutonium-cannon-shell"].order = "d[explosive-cannon-shell]-c[plutonium]"
--artillery
data.raw.recipe["artillery-shell"].subgroup = "ammo-artillery"
data.raw.recipe["rfw-fission-artillery-shell"].subgroup = "ammo-artillery"
data.raw.recipe["rfw-thermonuclear-artillery-shell"].subgroup = "ammo-artillery"
data.raw.recipe["rfw-fusion-artillery-shell"].subgroup = "ammo-artillery"
data.raw.recipe["rfw-antimatter-artillery-shell"].subgroup = "ammo-artillery"
--rocket launcher
data.raw.recipe["rocket"].subgroup = "ammo-rocket"
data.raw.recipe["explosive-rocket"].subgroup = "ammo-rocket"
data.raw.recipe["rfw-small-fusion-rocket"].subgroup = "ammo-rocket"
data.raw.recipe["rfw-small-antimatter-rocket"].subgroup = "ammo-rocket"
data.raw.recipe["heavy-rocket"].subgroup = "ammo-rocket"
data.raw.recipe["atomic-bomb"].subgroup = "ammo-rocket"
--data.raw.recipe["plutonium-atomic-bomb"].subgroup = "ammo-rocket"
data.raw.recipe["se-plague-bomb"].subgroup = "ammo-rocket"
data.raw.recipe["rfw-thermonuclear-bomb"].subgroup = "ammo-rocket"
data.raw.recipe["rfw-fusion-bomb"].subgroup = "ammo-rocket"
data.raw.recipe["rfw-antimatter-bomb"].subgroup = "ammo-rocket"
--aai ammo
data.raw.recipe["flamejet-ammo"].subgroup = "ammo-aai"
data.raw.recipe["flamethrower-ammo"].subgroup = "ammo-aai"
data.raw.recipe["rfw-plasma-thrower-deuterium-ammo"].subgroup = "ammo-aai"
data.raw.recipe["rfw-plasma-thrower-helium-3-ammo"].subgroup = "ammo-aai"
data.raw.recipe["laser-cannon-battery-focussed"].subgroup = "ammo-aai"
data.raw.recipe["laser-cannon-battery-piercing"].subgroup = "ammo-aai"
data.raw.recipe["electroshock-pulse-ammo"].subgroup = "ammo-aai"
--grappling gun
data.raw.recipe["grappling-gun-ammo"].subgroup = "ammo-grappling"
--se ammo
data.raw.recipe["se-bloater-ammo"].subgroup = "ammo-se"
data.raw.recipe["se-pheromone-ammo"].subgroup = "ammo-se"
data.raw.recipe["se-cryogun-ammo"].subgroup = "ammo-se"
data.raw.recipe["se-tesla-ammo"].subgroup = "ammo-se"
--