--Storage
data.raw.recipe["se-linked-container"].subgroup = "storage"
--Loaders
data.raw.recipe["kr-se-deep-space-loader-black"].subgroup = "belt-2"
data.raw.recipe["kr-se-deep-space-loader-blue"].subgroup = "belt-2"
data.raw.recipe["kr-se-deep-space-loader-cyan"].subgroup = "belt-2"
data.raw.recipe["kr-se-deep-space-loader-green"].subgroup = "belt-2"
data.raw.recipe["kr-se-deep-space-loader-magenta"].subgroup = "belt-2"
data.raw.recipe["kr-se-deep-space-loader-red"].subgroup = "belt-2"
data.raw.recipe["kr-se-deep-space-loader-white"].subgroup = "belt-2"
data.raw.recipe["kr-se-deep-space-loader-yellow"].subgroup = "belt-2"
--Transport Belts
data.raw.recipe["floating-belt"].subgroup = "transport-belt"
data.raw.recipe["floating-belt"].order = "z"
data.raw.recipe["se-deep-space-transport-belt"].subgroup = "transport-belt-2"
data.raw.recipe["se-deep-space-transport-belt-blue"].subgroup = "transport-belt-2"
data.raw.recipe["se-deep-space-transport-belt-cyan"].subgroup = "transport-belt-2"
data.raw.recipe["se-deep-space-transport-belt-green"].subgroup = "transport-belt-2"
data.raw.recipe["se-deep-space-transport-belt-magenta"].subgroup = "transport-belt-2"
data.raw.recipe["se-deep-space-transport-belt-red"].subgroup = "transport-belt-2"
data.raw.recipe["se-deep-space-transport-belt-white"].subgroup = "transport-belt-2"
data.raw.recipe["se-deep-space-transport-belt-yellow"].subgroup = "transport-belt-2"
--Underground Belt
data.raw.recipe["se-deep-space-underground-belt"].subgroup = "underground-belt-2"
data.raw.recipe["se-deep-space-underground-belt-blue"].subgroup = "underground-belt-2"
data.raw.recipe["se-deep-space-underground-belt-cyan"].subgroup = "underground-belt-2"
data.raw.recipe["se-deep-space-underground-belt-green"].subgroup = "underground-belt-2"
data.raw.recipe["se-deep-space-underground-belt-magenta"].subgroup = "underground-belt-2"
data.raw.recipe["se-deep-space-underground-belt-red"].subgroup = "underground-belt-2"
data.raw.recipe["se-deep-space-underground-belt-white"].subgroup = "underground-belt-2"
data.raw.recipe["se-deep-space-underground-belt-yellow"].subgroup = "underground-belt-2"
--Splitters
data.raw.recipe["se-deep-space-splitter"].subgroup = "splitter-2"
data.raw.recipe["se-deep-space-splitter-blue"].subgroup = "splitter-2"
data.raw.recipe["se-deep-space-splitter-cyan"].subgroup = "splitter-2"
data.raw.recipe["se-deep-space-splitter-green"].subgroup = "splitter-2"
data.raw.recipe["se-deep-space-splitter-magenta"].subgroup = "splitter-2"
data.raw.recipe["se-deep-space-splitter-red"].subgroup = "splitter-2"
data.raw.recipe["se-deep-space-splitter-white"].subgroup = "splitter-2"
data.raw.recipe["se-deep-space-splitter-yellow"].subgroup = "splitter-2"
--Inserters
data.raw.recipe["floating-burner-inserter"].subgroup = "inserter-2"
data.raw.recipe["floating-inserter"].subgroup = "inserter-2"
data.raw.recipe["floating-w93-hardened-inserter"].subgroup = "inserter-2"
data.raw.recipe["floating-fast-inserter"].subgroup = "inserter-2"
data.raw.recipe["floating-filter-inserter"].subgroup = "inserter-2"
data.raw.recipe["floating-stack-inserter"].subgroup = "inserter-2"
data.raw.recipe["floating-stack-filter-inserter"].subgroup = "inserter-2"
data.raw.recipe["floating-kr-superior-inserter"].subgroup = "inserter-2"
data.raw.recipe["floating-kr-superior-filter-inserter"].subgroup = "inserter-2"
--Electric Poles Light
data.raw.recipe["lighted-small-electric-pole"].subgroup = "lighted-poles"
data.raw.recipe["lighted-small-iron-electric-pole"].subgroup = "lighted-poles"
data.raw.recipe["lighted-medium-electric-pole"].subgroup = "lighted-poles"
data.raw.recipe["lighted-big-electric-pole"].subgroup = "lighted-poles"
data.raw.recipe["lighted-substation"].subgroup = "lighted-poles"
data.raw.recipe["lighted-kr-substation-mk2"].subgroup = "lighted-poles"
data.raw.recipe["lighted-se-addon-power-pole"].subgroup = "lighted-poles"
data.raw.recipe["lighted-se-pylon"].subgroup = "lighted-poles"
data.raw.recipe["lighted-se-pylon-substation"].subgroup = "lighted-poles"
--data.raw.recipe["lighted-se-pylon-construction"].subgroup = "lighted-poles"
--data.raw.recipe["lighted-se-pylon-construction-radar"].subgroup = "lighted-poles"
